base_url = "https://management.azure.com"
subscriptions_list_url = "https://management.azure.com/subscriptions"
resource_group_list_url = "https://management.azure.com/subscriptions/{}/resourcegroups"
storage_accounts_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Storage/storageAccounts"
container_list_url = "https://management.azure.com/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Storage/storageAccounts/{}/blobServices/default/containers"
role_definitions_list_url = "https://management.azure.com/{}/providers/Microsoft.Authorization/roleDefinitions"
log_profile_list_url = "https://management.azure.com/subscriptions/{}/providers/microsoft.insights/logprofiles"
key_vault_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.KeyVault/vaults'"
vault_policy_url = "https://management.azure.com/{}"
monitor_diagnostic_url= "https://management.azure.com/{}/providers/microsoft.insights/diagnosticSettings"
monitor_activity_log_url = "https://management.azure.com/subscriptions/{}/providers/microsoft.insights/eventtypes/management/values"
policy_assignments_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Authorization/policyAssignments/SecurityCenterBuiltIn"
security_contacts_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Security/securityContacts"
auto_provision_url = " https://management.azure.com/subscriptions/{}/providers/Microsoft.Security/autoProvisioningSettings"
pricing_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Security/pricings"
postgres_server_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.DBforPostgreSQL/servers"
sql_server_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Sql/servers"
mysql_server_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.DBforMySQL/servers"
mariadb_server_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.DBforMariaDB/servers"
sql_server_managed_instances_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Sql/managedInstances"
vm_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Compute/virtualMachines"
disk_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Compute/disks"
reserved_ip_list_url = "https://management.core.windows.net/{}/services/networking/reservedips"
redis_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Cache/Redis/"
vault_base_url = "https://{}.vault.azure.net/"
public_ips_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Network/publicIPAddresses"
list_vaults_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.RecoveryServices/vaults"
certificate_policy_url = "https://{}.vault.azure.net/certificates/{}/policy"
issuer_url = "https://{}.vault.azure.net/certificates/issuers/{}"
automation_accounts_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Automation/automationAccounts"
vm_scale_set_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Compute/virtualMachineScaleSets"
managed_clusters_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.ContainerService/managedClusters"
app_list_url= "https://management.azure.com/subscriptions/{}/providers/Microsoft.Web/sites"
service_bus_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.ServiceBus/namespaces"
network_sg_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Network/networkSecurityGroups"
network_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Network/virtualNetworks"
network_interface_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Network/networkInterfaces"
container_registry_list_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.ContainerRegistry/registries"
compliance_result_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Security/complianceResults"
manage_cluster_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.ContainerService/managedClusters"
contact_url = "https://management.azure.com/subscriptions/{}/providers/Microsoft.Security/securityContacts"
Azure_stream_analytics_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.StreamAnalytics/streamingJobs'"
Data_lake_analytics_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.DataLakeAnalytics/accounts'"
Data_lake_store_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.DataLakeStore/accounts'"
namespace_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.EventHub/namespaces'"
IoT_hub_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.Devices/IotHubs'"
workflows_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.Logic/workflows'"
search_services_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.Search/searchServices'"
Service_bus_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.ServiceBus/namespaces'"
batch_accounts_list_url = "https://management.azure.com/subscriptions/{}/resources?$filter=resourceType eq 'Microsoft.Batch/batchAccounts'"
Service_Fabric_url = " https://management.azure.com/subscriptions/{}/providers/Microsoft.ServiceFabric/clusters"
